# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
#####
jobs:
#####
  build:

    docker:
      - image: fdserr/clarc-cci-primary:0.0.1

    working_directory: ~/clarc

    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # cards build
      - run: lein cljsbuild once cards
      # prod build
      - run: lein cljsbuild once prod

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      # deploy cards to dev-cards s3 bucket
      - run: aws s3 sync ~/clarc/resources/public s3://clarc/ --delete
